services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    networks:
      - de-lakehouse-nyc-taxi-staging_default

networks:
  de-lakehouse-nyc-taxi-staging_default:
    external: true
volumes:
  grafana_data: { driver: local }
